export const ALL_COACHS_REQUEST = 'ALL_COACHS_REQUEST'
export const ALL_COACHS_SUCCESS = 'ALL_COACHS_SUCCESS'
export const ALL_COACHS_FAIL = 'ALL_COACHS_FAIL'

export const NEW_COACH_REQUEST = 'NEW_COACH_REQUEST'
export const NEW_COACH_SUCCESS = 'NEW_COACH_SUCCESS'
export const NEW_COACH_RESET = 'NEW_COACH_RESET'
export const NEW_COACH_FAIL = 'NEW_COACH_FAIL'

export const DELETE_COACH_REQUEST = 'DELETE_COACH_REQUEST'
export const DELETE_COACH_SUCCESS = 'DELETE_COACH_SUCCESS'
export const DELETE_COACH_RESET = 'DELETE_COACH_RESET'
export const DELETE_COACH_FAIL = 'DELETE_COACH_FAIL'

export const UPDATE_COACH_REQUEST = 'UPDATE_COACH_REQUEST'
export const UPDATE_COACH_SUCCESS = 'UPDATE_COACH_SUCCESS'
export const UPDATE_COACH_RESET = 'UPDATE_COACH_RESET'
export const UPDATE_COACH_FAIL = 'UPDATE_COACH_FAIL'

export const COACH_DETAILS_REQUEST = 'COACH_DETAILS_REQUEST'
export const COACH_DETAILS_SUCCESS = 'COACH_DETAILS_SUCCESS'
export const COACH_DETAILS_FAIL = 'COACH_DETAILS_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'